steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/go-docker-1996/docker-training','-']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/go-docker-1996/docker-training']