steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','gcr.io/go-docker-1996/docker_training','-']
  # Push the image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/go-docker-1996/docker_training']
  # Deploy image to Cloud Run